import {
	RESPONSE_FAILED_CODE,
	RESPONSE_SUCCESS_CODE,
	RESPONSE_SUCCESS_MESSAGE,
	RESPONSE_FAILED_MESSAGE
} from '@/common/constants'

export enum ResponseCode {
	FAILED = RESPONSE_FAILED_CODE,
	SUCCESS = RESPONSE_SUCCESS_CODE
}

export enum ResponseMsg {
	FAILED = RESPONSE_FAILED_MESSAGE,
	SUCCESS = RESPONSE_SUCCESS_MESSAGE
}
